base_dead_man_button: 4
gear_up_button: 6
gear_down_button: 7
board_button: 10
ad_button: 11
base_steering_axis: 3
base_speed_axis: 1
base_frame_id: base_link
max_steering_angle_deg: 30
gears: [ 0.3, 0.6, 1.0 ]
rate: 30.0
