base_dead_man_button: 4
base_steering_axis: 0
base_speed_axis: 3
base_frame_id: rc110_base
max_steering_angle_deg: 30
max_speed: 500 # TODO: fix this part when rc110 library can use [m/s] unit
max_acceleration: 1 # TODO: small value now until experiments to estimate acceleration rate is conducted
